#ifndef _CONFIG_H
#define _CONFIG_H

#define WINDOW_WIDTH 720
#define WINDOW_HEIGHT 720

#define START_BUTTON_WIDTH 200
#define START_BUTTON_HEIGHT 50
#define START_BUTTON_BOTTOM_PADDING 100

#define SOUND_VOLUME_SLIDER_WIDTH 150
#define SOUND_VOLUME_SLIDER_HEIGHT 10
#define SOUND_VOLUME_SLIDER_BOTTOM_PADDING 30

#define BOTTOM_BAR_HEIGHT 30
#define BOTTOM_BAR_COLOR ((Color) { .a = 255, .r = 20, .g = 20, .b = 20 })
#define BOTTOM_BAR_LINE_THICKNESS 4
#define BOTTOM_BAR_LINE_COLOR ((Color) { .a = 255, .r = 30, .g = 30, .b = 30 })

#define HEALTH_BAR_WIDTH 240
#define HEALTH_BAR_THICKNESS 20
#define HEALTH_BAR_PADDING 5

#define PLAYER_COLOR ((Color) { .a = 255, .r = 50, .g = 20, .b = 240 })
#define PLAYER_FORWARD_LINE_COLOR ((Color) { .a = 255, .r = 0, .g = 0, .b = 180 })
#define PLAYER_SPEED 15.0f
#define PLAYER_BACKWARDS_MULTIPLIER 0.5f
#define PLAYER_SIDEWAYS_MULTIPLIER 0.75f
#define PLAYER_ROTATE_SPEED 10.0f

#define PLAYER_SPEED_DAMPEN 0.95f
#define PLAYER_ROTATION_DAMPEN 0.95f

#define MAX_ASTEROID_COUNT 64
#define ASTEROID_DESPAWN_DISTANCE 120
#define ASTEROID_SPAWN_DISTANCE 80

#define ASTEROID_DELAY_MAX 4.0f
#define ASTEROID_DELAY_MIN 0.2f

#define ASTEROID_MAX_SIZE 90
#define ASTREOID_MIN_SIZE 10

#define ASTEROID_MAX_SPEED 110.0f
#define ASTEROID_MIN_SPEED 40.0f

#define ASTEROID_MAX_ROTATION_SPEED 90.0f
#define ASTEROID_MIN_ROTATION_SPEED 10.0f

#define ASTEROID_MAX_CENTER_OFFSET 200.0f

#define MAX_PROJECTILE_COUNT 3
#define PROJECTILE_MOVE_SPEED 500.0f

#define PROJECTILE_VISUAL_LENGTH 25.0f
#define PROJECTILE_DESPAWN_DISTANCE 120

#define MAX_PARTICLE_COUNT 1024

#endif